# Generated by Django 3.2 on 2021-05-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields={
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registracni_znacka', models.CharField(max_length=100)),
                ('znacka_vozidla', models.CharField(max_length=100)),
                ('pocet_kilometru', models.IntegerField()),
                ('datum_tech_kontroly', models.DateField()),
            },
        ),
    ]
