# Generated by Django 3.2 on 2021-05-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_zakaznik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_cas_vypujcky', models.DateTimeField()),
                ('datum_cas_konce_vypujcky', models.DateTimeField()),
                ('cena_vypujcky', models.IntegerField()),
            ],
        ),
    ]
