# Generated by Django 3.2 on 2021-05-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0006_pridaniautomobilu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PridaniVypujcky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_cas_vypujcky', models.DateTimeField()),
                ('datum_cas_konce_vypujcky', models.DateTimeField()),
                ('cena_vypujcky', models.IntegerField()),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.auto')),
                ('zakaznik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.zakaznik')),
            ],
        ),
    ]
